<a href="https://colab.research.google.com/github/manojfibby/CS460-Class-assignments/blob/main/100_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np

In [ ]:
#2
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
#3
x = np.zeros(10)

In [ ]:
#4
print(x.itemsize)

8


In [ ]:
#5
print(np.info(np.add))

None


In [ ]:
#6
x = np.zeros(10)
x[4] = 1

In [ ]:
#7
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#8
reversed_x = np.flip(x)
print(reversed_x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#9
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10
x = np.array([1,2,0,0,4,0])
x = np.nonzero(x)
print(x)

(array([0, 1, 4]),)


In [ ]:
#11
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#12
x = np.random.rand(3,3,3)
print(x)

[[[0.85897969 0.28258451 0.22001236]
  [0.75351042 0.56239294 0.44298132]
  [0.42813977 0.13607074 0.71387699]]

 [[0.01920378 0.79069735 0.52034053]
  [0.40320993 0.20613494 0.87071616]
  [0.33503095 0.48155968 0.38467427]]

 [[0.74916081 0.55843056 0.62885584]
  [0.44455589 0.97046621 0.8189232 ]
  [0.41951061 0.63708492 0.07763778]]]


In [ ]:
#13
x = np.random.rand(10,10)
print("min:",x.min())
print("min:",x.max())

min: 8.028974991369786e-05
min: 0.9722578340043141


In [ ]:
#14
x = np.random.rand(30)
print("mean:",x.mean())

mean: 0.5691786093089648


In [ ]:
#15
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#16
x = np.ones((4,4))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
#18 
x = np.diag(1+np.arange(4), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#19
x = np.zeros((8,8))
sz = x.shape[0]
for i in range(sz):
  for j in range(sz):
    if (i+j)%2 == 1:
      x[i][j] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#20
x = np.zeros((6,7,8))
print(np.unravel_index(100,x.shape))

(1, 5, 4)


In [ ]:
#21
x = np.array([[0,1],[1,0]])
x = np.tile(x,(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#22
x = np.random.rand(12).reshape(3,4)
x_min = x.min()
x_max = x.max()
x = (x - x_min)/(x_max - x_min)
print(x)

[[0.19936469 0.95287309 1.         0.        ]
 [0.28962674 0.06191265 0.84452686 0.06967419]
 [0.78395181 0.3174749  0.6006695  0.2063527 ]]


In [ ]:
#23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [ ]:
#24
x = np.random.rand(15).reshape(5,3)
y = np.random.rand(6).reshape(3,2)
z = x.dot(y)
print(z)

[[1.18527923 0.50931019]
 [1.39842454 0.54992305]
 [0.88744226 0.46684709]
 [1.34917782 0.5723654 ]
 [0.83898962 0.41022041]]


In [ ]:
#25
x = np.arange(10)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [ ]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) -----> not legal

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#29
x = np.random.rand(10)
print(x)
y = np.copysign(np.ceil(np.abs(x)), x)
print(y)

[0.30130232 0.9418313  0.13455259 0.16617778 0.33520313 0.26230442
 0.55290718 0.43902534 0.42780401 0.56606639]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#30
x = [1,2,3,4,5]
y = [1,3,5,7,9]
print(np.intersect1d(x,y))

[1 3 5]


In [ ]:
#31
defaults = np.seterr(all="ignore")

In [ ]:
#32
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [ ]:
#33
yes = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tom  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [ ]:
#34
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35
a = np.ones(5)*3
b = np.ones(5)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[-7.5 -7.5 -7.5 -7.5 -7.5]


In [ ]:
#36
x = np.random.rand(3)

print (np.trunc(x))

print (np.floor(x))

print (np.ceil(x)-1)

print (x.astype(int))

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0 0 0]


In [ ]:
#37
x = np.zeros((5,5))
x = x+[0,1,2,3,4]
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#38
def generate():
    for i in range(10):
        yield i

x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#39
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#40
x = np.random.rand(10)
print(np.sort(x))

[0.0165907  0.24163001 0.39700295 0.42494565 0.60321341 0.62180983
 0.62463501 0.68024662 0.68333563 0.78219072]


In [ ]:
#41
x = np.arange(5)
print(np.add.reduce(x))

10


In [ ]:
#42
x = np.zeros(4)
y = np.zeros(5)
equal = np.array_equal(x,y)
print(equal)

False


In [ ]:
#43
x = np.zeros(3)
x.flags.writeable = False
#x[0] = 1 -> returns error

In [ ]:
#44

a = np.random.random((10,2))
x,y = a[:,0], a[:,1]

r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)
print(r)
print(theta)

[0.56790583 0.95894253 0.56740675 1.03447886 1.13426781 0.74572533
 1.22885132 0.87852448 0.83691945 0.68784065]
[1.52811775 0.73872121 1.07692704 1.00343129 0.78634825 0.94199306
 0.87587007 0.62009266 1.05519674 0.2661908 ]


In [ ]:
#45
x = np.random.rand(10)
x[x.argmax()] = 0
print(x)

[0.66660411 0.34754101 0.26689102 0.10444042 0.24641496 0.90319312
 0.         0.65838806 0.82499727 0.15870575]


In [ ]:
#46
x = np.zeros((3,3), [('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(x)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [ ]:
#47
x = np.arange(3)
y = np.random.random(3)
c = 1.0 / np.subtract.outer(x, y)
print(c)

[[-2.97969767 -3.16708323 -1.53194029]
 [ 1.50512763  1.46144974  2.87991024]
 [ 0.60081874  0.59373536  0.74226208]]


In [ ]:
#48
print("int8:")
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)
print()

print("int32:")
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print("")

print("int64:")
print(np.iinfo(np.int64).min)
print(np.iinfo(np.int64).max)
print("")

print("float32:")
print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print("")

print("float64")
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)
print("")

int8:
-128
127

int32:
-2147483648
2147483647

int64:
-9223372036854775808
9223372036854775807

float32:
-3.4028235e+38
3.4028235e+38

float64
-1.7976931348623157e+308
1.7976931348623157e+308



In [ ]:
#49
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((25,25))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
#50
x = np.arange(10)
v = np.random.uniform(0,10)
index = (np.abs(x-v)).argmin()
print(v,x[index])

9.832853568743818 9


In [ ]:
#51
x = np.zeros(3, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
#52
import scipy.spatial

x = np.random.random((100,2))
d = scipy.spatial.distance.cdist(x,x)
print(d)

[[0.         0.34178402 0.36298073 0.18722397 0.12719898 0.10838823
  0.65859076 0.76445579 0.49449493 0.02849607 0.71129516 0.11917987
  0.82436478 0.81435477 0.21626305 0.60242563 0.84181033 0.56022232
  0.27042209 0.19785326 0.85597069 0.26429453 0.2129944  0.2086617
  0.47326865 0.8941733  0.88528101 0.49764633 0.26330319 0.11497993
  0.65697711 0.63943005 0.17529859 0.46715344 0.86176602 0.81850452
  0.69452746 0.10624766 0.67228369 0.17436636 0.45347636 0.77761806
  0.91992203 0.31321696 0.80737249 0.234355   0.69386991 0.3949036
  0.66128693 0.46255148 0.5370658  0.18018358 0.10334007 0.69513415
  0.80390213 0.30707885 0.67530507 0.63929672 0.76598303 0.24315023
  0.38278329 0.59941525 0.25937085 0.20678238 0.24189334 0.43952282
  0.34974234 0.21541763 0.39541726 0.74589462 0.34052067 0.26105129
  0.74916035 0.70998769 0.19253709 0.40701447 0.17359074 0.39564732
  0.71226202 0.67641738 0.64619903 0.73946426 0.33102676 0.49339908
  0.78690075 0.23719996 0.22115516 0.2617613  0.62

In [ ]:
#53
floatarr = np.array([1.2,2.3,3.4])
intarr = floatarr.astype(np.int32, copy=False)
print(intarr)

[1 2 3]


In [ ]:
#54
# Ans: x = np.genfromtxt(abc.xyz, delimiter=",", dtype=np.int)

In [ ]:
#55
x = np.ones(12).reshape(3,4)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 1.0
(0, 1) 1.0
(0, 2) 1.0
(0, 3) 1.0
(1, 0) 1.0
(1, 1) 1.0
(1, 2) 1.0
(1, 3) 1.0
(2, 0) 1.0
(2, 1) 1.0
(2, 2) 1.0
(2, 3) 1.0


In [ ]:
#56
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D generic gaussian-like array:")
print(g)

2D generic gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73

In [ ]:
#57
p = [1,2,3]
x = np.zeros((5,5))
for i in p:
  np.put(x, np.random.choice(range(25), 1, replace=False),i)
print(x)

[[0. 0. 3. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#58
x = np.random.rand(3, 4)
x = x - x.mean(axis=1, keepdims=True)
print(x)

[[ 0.378556   -0.44348019 -0.15436792  0.21929212]
 [ 0.13820726 -0.03997987 -0.19523455  0.09700716]
 [ 0.29364955 -0.45422127 -0.23421283  0.39478455]]


In [ ]:
#59
x = np.random.rand(12).reshape(3,4)
print(x)
print(x[x[:,2].argsort()]) # Sorting based on 2nd column

[[5.23798984e-01 5.47538079e-03 3.83735682e-03 8.17351307e-01]
 [8.96129036e-01 2.10508628e-01 7.07422971e-01 4.62413270e-01]
 [9.17045475e-05 1.06309273e-01 1.11537993e-01 4.76554808e-01]]
[[5.23798984e-01 5.47538079e-03 3.83735682e-03 8.17351307e-01]
 [9.17045475e-05 1.06309273e-01 1.11537993e-01 4.76554808e-01]
 [8.96129036e-01 2.10508628e-01 7.07422971e-01 4.62413270e-01]]


In [ ]:
#60
x = np.ones((3,3))
print((~Z.any(axis=0)).any())

False


In [ ]:
#61
x = np.random.rand(5)
v = 0.5
index = (np.abs(x-v)).argmin()
print(v,x[index])

0.5 0.5625073107677551


In [ ]:
#62
x = np.arange(3).reshape(3,1)
y = np.arange(3).reshape(1,3)
it = np.nditer([x,y,None])
for a,b,c in it: c[...] = a + b
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63
class NamedArray(np.ndarray):
  
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(5), "arr10")
print(x.name)

arr10


In [ ]:
#64
x = np.random.rand(10)
y = [1,2,3,4,5]
np.add.at(x, y, 1)
print(x)

[0.94853331 1.72259463 1.58680616 1.00319165 1.02330655 1.33136519
 0.09886901 0.03933661 0.17978295 0.19719607]


In [ ]:
#65
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(X,F)


[1, 2, 3, 4, 5, 6] [0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#66
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [ ]:
#67
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[62 40 37 45]
 [58 63 64 78]
 [46 44 46 60]]
[[62 40 37 45]
 [58 63 64 78]
 [46 44 46 60]]


In [ ]:
#68
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.55446403 0.41737426 0.46615378 0.31463246 0.60071164 0.50226488
 0.46967542 0.63348486 0.4816909  0.69232161]
0    0.554464
1    0.417374
2    0.466154
3    0.314632
4    0.600712
5    0.502265
6    0.469675
7    0.633485
8    0.481691
9    0.692322
dtype: float64


In [ ]:
#69
x = np.random.rand(12).reshape(3,4)
y = np.random.rand(12).reshape(4,3)

z = np.diag(x.dot(y))
print(z)

[1.06315195 0.91487786 0.63515853]


In [ ]:
#70
x = np.array([1,2,3,4,5])
n = x.shape
out = np.zeros((4*5),dtype=x.dtype)
out[::4] = x
print(out)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


In [ ]:
#71
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
z = x * y[:,:,None]
print(z)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
#72
x = np.arange(9).reshape(3,3)
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
#73
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 36) ( 0, 40) ( 5,  7) ( 5, 64) ( 6, 19) ( 6, 86) ( 7, 64) (12, 38)
 (12, 89) (13, 32) (13, 82) (15, 38) (15, 59) (19, 86) (32, 82) (36, 40)
 (38, 59) (38, 89) (42, 48) (42, 96) (48, 96) (53, 68) (53, 95) (67, 77)
 (67, 87) (68, 95) (69, 72) (69, 88) (72, 88) (77, 87)]


In [ ]:
#74
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
print(y)

[1 1 2 3 4 4 6]


In [ ]:
#75
def moving_average(arr, winsize) :
    avg_arr = np.cumsum(arr, dtype=float)
    avg_arr[winsize:] = avg_arr[winsize:] - avg_arr[:-winsize]

    return avg_arr[winsize - 1:] / winsize

x = np.arange(10)
print(moving_average(x, 3))

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
#76
from numpy.lib import stride_tricks

def shiftandadd(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

x = np.arange(10)
ans = shiftandadd(x, 3)
print(ans)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#77
x = np.random.uniform(-1.0,1.0,10)
print(x)
np.negative(x, out=x)
print(x)

[-0.12664457 -0.22701423  0.29945253 -0.37540162  0.04115777 -0.48746646
  0.77016631 -0.82510469  0.69509064  0.22766662]
[ 0.12664457  0.22701423 -0.29945253  0.37540162 -0.04115777  0.48746646
 -0.77016631  0.82510469 -0.69509064 -0.22766662]


In [ ]:
#78
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.73249554  6.46120291 10.43385551  1.76722791  0.29080602  1.67912162
  1.53256984  6.11502361  1.41880994  1.993267  ]


In [ ]:
#79
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.083549   11.94620204 12.33737412  4.02978991  9.51959406  2.55588896
   0.359253    9.87284953 15.21304232 13.06119993]
 [ 7.61160686  0.81312215  7.67396094  4.57855826  4.022804    2.68796623
   4.49854503  5.98219555  1.77494748  2.42152384]
 [ 9.57971354  9.1992806  16.15161329 10.15948998  4.9762781   6.05279045
   7.00546527 14.08944503 11.07320706 12.75126573]
 [ 5.04190447  1.74715092  0.21082038  6.53670796  1.67457309 10.1041008
   8.04400073  2.4896675   6.75386486  0.93055576]
 [11.95309824  4.66509924 14.80685464 10.74432719  0.05826495  4.48928984
   9.14149837 13.03459886  6.21696733  9.09876472]
 [ 1.91100883 11.0154314  11.55723698  3.52090861  8.68033412  1.75097535
   0.581861    9.12753559 14.34659983 12.10420122]
 [ 4.88552417  6.90584107  3.50182396  4.47884054  6.53255857  6.22973333
   7.61175548  1.00003844 11.71417454  5.98337167]
 [ 3.55319011  1.95779373  6.50308968  1.73494468  0.34410647  3.64559934
   0.57986259  4.53655462  5.25831286  3.83448754]
 

In [ ]:
#80
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 1 8 9 1 8 1 6 5 6]
 [9 8 2 1 3 4 3 5 9 7]
 [1 8 5 4 7 7 8 3 0 5]
 [1 5 6 7 2 4 0 1 5 2]
 [6 7 0 2 0 3 6 2 8 4]
 [1 9 2 9 3 8 8 0 7 8]
 [3 4 1 5 6 3 5 9 6 3]
 [3 8 5 9 3 9 5 5 1 8]
 [9 7 5 7 9 9 9 0 5 8]
 [4 8 8 2 3 8 1 6 8 3]]
[[0 0 0 0 0]
 [0 4 1 8 9]
 [0 9 8 2 1]
 [0 1 8 5 4]
 [0 1 5 6 7]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [ ]:
#81
from numpy.lib import stride_tricks

def shiftandadd(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ans = shiftandadd(x,4)
print(ans)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
#82
x = np.random.rand(25).reshape(5,5)
U, S, V = np.linalg.svd(x) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

5


In [ ]:
#83
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

3


In [ ]:
#84
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 1 1]
   [4 2 3]
   [2 2 3]]

  [[1 1 4]
   [2 3 1]
   [2 3 3]]

  [[1 4 0]
   [3 1 4]
   [3 3 1]]

  [[4 0 1]
   [1 4 3]
   [3 1 4]]

  [[0 1 4]
   [4 3 3]
   [1 4 1]]

  [[1 4 3]
   [3 3 3]
   [4 1 1]]

  [[4 3 0]
   [3 3 0]
   [1 1 0]]

  [[3 0 3]
   [3 0 1]
   [1 0 3]]]


 [[[4 2 3]
   [2 2 3]
   [1 3 1]]

  [[2 3 1]
   [2 3 3]
   [3 1 0]]

  [[3 1 4]
   [3 3 1]
   [1 0 4]]

  [[1 4 3]
   [3 1 4]
   [0 4 3]]

  [[4 3 3]
   [1 4 1]
   [4 3 1]]

  [[3 3 3]
   [4 1 1]
   [3 1 2]]

  [[3 3 0]
   [1 1 0]
   [1 2 0]]

  [[3 0 1]
   [1 0 3]
   [2 0 4]]]


 [[[2 2 3]
   [1 3 1]
   [0 1 1]]

  [[2 3 3]
   [3 1 0]
   [1 1 2]]

  [[3 3 1]
   [1 0 4]
   [1 2 3]]

  [[3 1 4]
   [0 4 3]
   [2 3 4]]

  [[1 4 1]
   [4 3 1]
   [3 4 2]]

  [[4 1 1]
   [3 1 2]
   [4 2 4]]

  [[1 1 0]
   [1 2 0]
   [2 4 3]]

  [[1 0 3]
   [2 0 4]
   [4 3 3]]]


 [[[1 3 1]
   [0 1 1]
   [3 3 3]]

  [[3 1 0]
   [1 1 2]
   [3 3 4]]

  [[1 0 4]
   [1 2 3]
   [3 4 1]]

  [[0 4 3]
   [2 3 4]
   [4 1 0]]

  [[4 3 1]
   

In [ ]:
#85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 18  6 13 17]
 [18  4 12 14  6]
 [ 6 12  5 42  4]
 [13 14 42  5 11]
 [17  6  4 11  9]]


In [ ]:
#86
p = 10
n = 5
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]]


In [ ]:
#87
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
#88
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
#89
x = np.random.randint(0,100,50)
n = 5
print (x[np.argpartition(-x,n)[:n]])

[98 97 97 97 89]


In [ ]:
#90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
#91
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
#92
x = 99

print("By Method 1: ",x**3)
print("By Method 2: ",np.power(x,3))
print("By Method 3: ",x*x*x)

In [ ]:
#93
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[4 5]


In [ ]:
#94
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 1]
 [0 3 3]
 [2 1 4]
 [4 1 2]
 [2 4 4]
 [1 2 1]
 [3 3 0]
 [0 2 1]
 [4 1 4]
 [0 3 2]]
[[3 1 1]
 [0 3 3]
 [2 1 4]
 [4 1 2]
 [2 4 4]
 [1 2 1]
 [3 3 0]
 [0 2 1]
 [4 1 4]
 [0 3 2]]
[[3 1 1]
 [0 3 3]
 [2 1 4]
 [4 1 2]
 [2 4 4]
 [1 2 1]
 [3 3 0]
 [0 2 1]
 [4 1 4]
 [0 3 2]]


In [ ]:
#95

x = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [ ]:
#96
x = np.zeros(12).reshape(3,4)
uniquex = np.unique(x, axis=0)
print(uniquex)

[[0. 0. 0. 0.]]


In [ ]:
#97
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   

array([[0.05139669, 0.14606215, 0.07026604, 0.03761974, 0.04876573,
        0.00690973, 0.04838822, 0.1737582 , 0.06665453, 0.13926283],
       [0.04815166, 0.13684024, 0.06582966, 0.03524455, 0.04568682,
        0.00647347, 0.04533313, 0.16278764, 0.06244617, 0.13047021],
       [0.20978261, 0.59617267, 0.28680044, 0.15355012, 0.19904402,
        0.02820301, 0.19750313, 0.70921784, 0.27205957, 0.5684203 ],
       [0.18064142, 0.51335751, 0.2469606 , 0.13222026, 0.17139454,
        0.02428529, 0.1700677 , 0.61069943, 0.23426741, 0.48946026],
       [0.01564075, 0.04444882, 0.02138297, 0.01144823, 0.01484012,
        0.00210273, 0.01472523, 0.05287713, 0.02028393, 0.04237969],
       [0.03052909, 0.08675938, 0.04173729, 0.02234573, 0.02896633,
        0.00410431, 0.02874209, 0.10321054, 0.03959209, 0.08272066],
       [0.26511432, 0.75341758, 0.36244616, 0.19405009, 0.25154334,
        0.03564176, 0.24959603, 0.89627926, 0.34381728, 0.71834533],
       [0.25201376, 0.71618766, 0.3445359

In [ ]:
#98
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [ ]:
#99
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
#100
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.16831053  0.17361472]
